# Generated by Django 2.2 on 2019-04-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='tag',
            new_name='tags',
        ),
    ]
